### ISSUE TITLE
min is builtin, loop not necessary

### ISSUE THREAD

**Issue by DrPaulBrewer** [compute-io/min#3]
The loop in this function is correct, but is slower than appropriate use of the javascript builtin Math.min() function.

A typical call looks like this:  `m = Math.min(3,1,4,1,5,9)`  

Math.min expects each parameter to be a number.

To use it on an array `x`, call it with javascript's Function.apply builtin like this:  `Math.min.apply(null, x)`

`Math.min.apply(null, [3,1,4,1,5,9])`  returns 1.

**Comment by kgryte** [comment]
@DrPaulBrewer We are aware of the built-in implementation. The userland implementation is **intentional**.

Re: performance. Which implementation is faster **depends** on the engine. For instance, on my Macbook Pro and given the following performance test:

``` javascript

// Number of iterations:
var N = 1e7;

// Test array length:
var T = 100;

var i;
var d;

// Create a test data array...
d = new Array( T );
for ( i = 0; i < T; i++ ) {
    d[ i ] = Math.random()*100 - 50;
}

// Userland implementation:
function min( arr ) {
    if ( !Array.isArray( arr ) ) {
        throw new TypeError( 'min()::invalid input argument. Must provide an array.' );
    }
    var len = arr.length,
        val = arr[ 0 ];

    for ( var i = 1; i < len; i++ ) {
        if ( arr[ i ] < val ) {
            val = arr[ i ];
        }
    }
    return val;
}

// Performance test for the userland implementation:
function test1() {
    var val;
    var t2;
    var t1;
    var i;

    t1 = performance.now();
    for ( i = 0; i < N; i++ ) {
        val = min( d ); 
    }
    t2 = performance.now();
    console.log( 'Userland: %d ms. Minimum value: %d.', t2 - t1, val );
}

// Performance test for built-in implementation:
function test2() {
    var val;
    var t1;
    var t2;
    var i;

    t1 = performance.now();
    for ( i = 0; i < N; i++ ) {
        val = Math.min.apply( null, d ); 
    }
    t2 = performance.now();
    console.log( 'Built-in: %d ms. Minimum value: %d.', t2 - t1, val );
}

// Run the performance tests:
test1();
test2();
```

for Chrome Version `49.0.2623.112 (64-bit)`, I get

```
Userland: 17692 ms. Minimum value: -50.
Built-in: 82817 ms. Minimum value: -50.
```

In which case, the **userland** implementation is faster when handling an `array` of length `100`. On Firefox Version `43.0.3` (and `46.0.1`), I get

```
Userland: 19220 ms. Minimum value: -49.
Built-in: 14229 ms. Minimum value: -49.
```

In which case, the **built-in** implementation is faster, but not mind-blowingly so. 

Note that performance results also vary depending on the test `array` length. For shorter `arrays`, Chrome's built-in implementation performs better. 

In general, we intentionally avoid built-ins due to buggy implementations and a desire to have algorithmic control. Feel free to use the built-in. YMMV.

Closing...

**Comment by kgryte** [comment]
Also note that, if you remove the type check in the userland implementation, in Firefox, the userland implementation is comparable to the built-in:

```
Userland: 13925 ms. Minimum value: -49.
Built-in: 12041 ms. Minimum value: -49.
```
